# backend/core/config.py
import os
from dotenv import load_dotenv

load_dotenv()

# --- SYSTEM & ENVIRONMENT SETTINGS ---
SAGE_ENV = os.getenv("SAGE_ENV", "development").lower()
IS_PRODUCTION = (SAGE_ENV == "production")
SAGE_DEBUG = os.getenv("SAGE_DEBUG", "false").lower() in ("true", "1", "yes") if IS_PRODUCTION else True

# --- CORS & NETWORK SECURITY ---
DEFAULT_DEV_ORIGINS = "http://localhost:3000,http://127.0.0.1:3000,http://localhost:8000,http://127.0.0.1:8000"
raw_origins = os.getenv("SAGE_ALLOWED_ORIGINS", DEFAULT_DEV_ORIGINS)
SAGE_ALLOWED_ORIGINS = [o.strip() for o in raw_origins.split(",") if o.strip()]

raw_hosts = os.getenv("SAGE_ALLOWED_HOSTS", "localhost,127.0.0.1")
SAGE_ALLOWED_HOSTS = [h.strip() for h in raw_hosts.split(",") if h.strip()]

# --- AUTHENTICATION CONFIGURATION ---
SAGE_AUTH_ENABLED = os.getenv("SAGE_AUTH_ENABLED", "false" if not IS_PRODUCTION else "true").lower() in ("true", "1", "yes")
SAGE_AUTH_PROVIDER = os.getenv("SAGE_AUTH_PROVIDER", "development" if not IS_PRODUCTION else "jwt").lower()
SAGE_AUTH_ISSUER = os.getenv("SAGE_AUTH_ISSUER", "https://auth.sagecommand.io")
SAGE_AUTH_AUDIENCE = os.getenv("SAGE_AUTH_AUDIENCE", "sagecommand_api")
SAGE_SECRET_KEY = os.getenv("SAGE_SECRET_KEY", "sagecommand_default_dev_secret_key_change_in_production")
raw_jwt_algs = os.getenv("SAGE_JWT_ALGORITHMS", "HS256,RS256")
SAGE_JWT_ALGORITHMS = [a.strip() for a in raw_jwt_algs.split(",") if a.strip()]

# --- REQUEST & RESOURCE BOUNDARIES ---
SAGE_MAX_REQUEST_SIZE = int(os.getenv("SAGE_MAX_REQUEST_SIZE", 10 * 1024 * 1024))  # 10 MB default limit
SAGE_RATE_LIMIT = int(os.getenv("SAGE_RATE_LIMIT", 60))  # 60 requests per minute
SAGE_DB_CONNECTION_TIMEOUT = int(os.getenv("SAGE_DB_CONNECTION_TIMEOUT", 10))  # 10 seconds
SAGE_DB_POOL_SIZE = int(os.getenv("SAGE_DB_POOL_SIZE", 5))

# --- DATABASE GATEWAY SECURITY CONFIGURATION ---
SAGE_DB_NETWORK_POLICY = os.getenv("SAGE_DB_NETWORK_POLICY", "RESTRICTED").upper()
raw_allowed_db_hosts = os.getenv("SAGE_DB_ALLOWED_HOSTS") or os.getenv("SAGE_ALLOWED_DB_HOSTS") or ("localhost,127.0.0.1" if not IS_PRODUCTION else "")
SAGE_DB_ALLOWED_HOSTS = [h.strip().lower() for h in raw_allowed_db_hosts.split(",") if h.strip()]
raw_allowed_db_ports = os.getenv("SAGE_DB_ALLOWED_PORTS", "5432,3306,1433")
SAGE_DB_ALLOWED_PORTS = [int(p.strip()) for p in raw_allowed_db_ports.split(",") if p.strip().isdigit()]
SAGE_DB_SSL_POLICY = os.getenv("SAGE_DB_SSL_POLICY", "REQUIRED").upper()
SAGE_DB_MAX_SAMPLE_ROWS = int(os.getenv("SAGE_DB_MAX_SAMPLE_ROWS", 5))
SAGE_DB_IDLE_TIMEOUT = int(os.getenv("SAGE_DB_IDLE_TIMEOUT", 1800))  # 30 minutes
SAGE_DB_MAX_LIFETIME = int(os.getenv("SAGE_DB_MAX_LIFETIME", 86400))  # 24 hours

# --- SENSITIVE DATA & LOGGING ---
SAGE_LOG_SENSITIVE_DATA = os.getenv("SAGE_LOG_SENSITIVE_DATA", "false").lower() in ("true", "1", "yes")

# --- LLM API KEYS ---
GOOGLE_API_KEY = os.getenv("GOOGLE_API_KEY") or os.getenv("GEMINI_API_KEY")
GROQ_API_KEY = os.getenv("GROQ_API_KEY")
TAVILY_API_KEY = os.getenv("TAVILY_API_KEY")

# --- DATABASE & LEDGER PATHS ---
DEFAULT_DB_PATH = "./dynamic_datacore.sqlite"
MEMORY_DB_PATH = "sage_memory.sqlite"
SAGE_AUDIT_LEDGER_DB_PATH = os.getenv("SAGE_AUDIT_LEDGER_DB_PATH", "sage_audit_ledger.sqlite")
SAGE_AUDIT_MAX_PAYLOAD_SIZE = int(os.getenv("SAGE_AUDIT_MAX_PAYLOAD_SIZE", 65536))  # 64 KB

# --- TRANSACTION & ROLLBACK CONFIGURATION ---
SAGE_TRANSACTIONS_DB_PATH = os.getenv("SAGE_TRANSACTIONS_DB_PATH", "sage_transactions.sqlite")
SAGE_TRANSACTION_DEFAULT_TTL_SECONDS = int(os.getenv("SAGE_TRANSACTION_DEFAULT_TTL_SECONDS", 3600))  # 1 hour
SAGE_TRANSACTION_MAX_PAYLOAD_SIZE = int(os.getenv("SAGE_TRANSACTION_MAX_PAYLOAD_SIZE", 65536))  # 64 KB

# --- INDUSTRIAL ONTOLOGY CONFIGURATION ---
SAGE_ONTOLOGY_DB_PATH = os.getenv("SAGE_ONTOLOGY_DB_PATH", "sage_ontology.sqlite")
SAGE_ONTOLOGY_MAX_ENTITIES_PER_QUERY = int(os.getenv("SAGE_ONTOLOGY_MAX_ENTITIES_PER_QUERY", 100))

# --- OPERATIONAL KNOWLEDGE GRAPH CONFIGURATION (Prompt 12) ---
SAGE_KNOWLEDGE_GRAPH_DB_PATH = os.getenv("SAGE_KNOWLEDGE_GRAPH_DB_PATH", "sage_knowledge_graph.sqlite")
SAGE_KG_MAX_TRAVERSAL_DEPTH = int(os.getenv("SAGE_KG_MAX_TRAVERSAL_DEPTH", 5))
SAGE_KG_MAX_TRAVERSAL_NODES = int(os.getenv("SAGE_KG_MAX_TRAVERSAL_NODES", 200))
SAGE_KG_MAX_TRAVERSAL_EDGES = int(os.getenv("SAGE_KG_MAX_TRAVERSAL_EDGES", 500))
SAGE_KG_FRESHNESS_STALE_SECONDS = int(os.getenv("SAGE_KG_FRESHNESS_STALE_SECONDS", 300))  # 5 minutes
SAGE_KG_FRESHNESS_EXPIRED_SECONDS = int(os.getenv("SAGE_KG_FRESHNESS_EXPIRED_SECONDS", 3600))  # 1 hour

# --- DIGITAL TWIN CONFIGURATION (Prompt 13) ---
SAGE_DIGITAL_TWIN_DB_PATH = os.getenv("SAGE_DIGITAL_TWIN_DB_PATH", "sage_digital_twin.sqlite")
SAGE_DT_FRESHNESS_STALE_SECONDS = int(os.getenv("SAGE_DT_FRESHNESS_STALE_SECONDS", 300))  # 5 minutes
SAGE_DT_FRESHNESS_EXPIRED_SECONDS = int(os.getenv("SAGE_DT_FRESHNESS_EXPIRED_SECONDS", 3600))  # 1 hour
SAGE_DT_MAX_SNAPSHOT_ENTITIES = int(os.getenv("SAGE_DT_MAX_SNAPSHOT_ENTITIES", 500))
SAGE_DT_MAX_HISTORY_RECORDS = int(os.getenv("SAGE_DT_MAX_HISTORY_RECORDS", 200))

# --- DATA QUALITY CONFIGURATION (Prompt 14) ---
SAGE_DATA_QUALITY_DB_PATH = os.getenv("SAGE_DATA_QUALITY_DB_PATH", "sage_data_quality.sqlite")
SAGE_DQ_MAX_ENTITIES_PER_ASSESSMENT = int(os.getenv("SAGE_DQ_MAX_ENTITIES_PER_ASSESSMENT", 1000))
SAGE_DQ_MAX_RULES_PER_ASSESSMENT = int(os.getenv("SAGE_DQ_MAX_RULES_PER_ASSESSMENT", 100))

# --- EVENT DRIVEN ARCHITECTURE CONFIGURATION (Prompt 17) ---
SAGE_EVENT_DELIVERY_DB_PATH = os.getenv("SAGE_EVENT_DELIVERY_DB_PATH", "sage_event_delivery.sqlite")
SAGE_EVENT_BUS_ENABLED = os.getenv("SAGE_EVENT_BUS_ENABLED", "true").lower() in ("true", "1", "yes")
SAGE_EVENT_BUS_QUEUE_SIZE = int(os.getenv("SAGE_EVENT_BUS_QUEUE_SIZE", 1000))
SAGE_EVENT_BUS_MAX_WORKERS = int(os.getenv("SAGE_EVENT_BUS_MAX_WORKERS", 5))
SAGE_EVENT_BUS_MAX_RETRIES = int(os.getenv("SAGE_EVENT_BUS_MAX_RETRIES", 3))

# --- INCIDENT MANAGEMENT CONFIGURATION (Prompt 18) ---
SAGE_INCIDENT_DB_PATH = os.getenv("SAGE_INCIDENT_DB_PATH", "sage_incidents.sqlite")
SAGE_EVENT_BUS_MAX_CONCURRENT_DELIVERIES = int(os.getenv("SAGE_EVENT_BUS_MAX_CONCURRENT_DELIVERIES", 100))

# --- ROOT-CAUSE ANALYSIS CONFIGURATION (Prompt 19) ---
SAGE_RCA_DB_PATH = os.getenv("SAGE_RCA_DB_PATH", "sage_rca.sqlite")
SAGE_RCA_MAX_EVIDENCE = int(os.getenv("SAGE_RCA_MAX_EVIDENCE", 1000))
SAGE_RCA_MAX_GRAPH_DEPTH = int(os.getenv("SAGE_RCA_MAX_GRAPH_DEPTH", 5))
SAGE_RCA_MAX_CANDIDATES = int(os.getenv("SAGE_RCA_MAX_CANDIDATES", 50))

# --- BLAST-RADIUS INTELLIGENCE CONFIGURATION (Prompt 20) ---
SAGE_BLAST_RADIUS_DB_PATH = os.getenv("SAGE_BLAST_RADIUS_DB_PATH", "sage_blast_radius.sqlite")
SAGE_BLAST_RADIUS_MAX_DEPTH = int(os.getenv("SAGE_BLAST_RADIUS_MAX_DEPTH", 5))
SAGE_BLAST_RADIUS_MAX_NODES = int(os.getenv("SAGE_BLAST_RADIUS_MAX_NODES", 200))
SAGE_BLAST_RADIUS_MAX_PATHS = int(os.getenv("SAGE_BLAST_RADIUS_MAX_PATHS", 500))
SAGE_BLAST_RADIUS_MAX_EVIDENCE = int(os.getenv("SAGE_BLAST_RADIUS_MAX_EVIDENCE", 1000))

# --- PREDICTIVE MAINTENANCE CONFIGURATION (Prompt 21) ---
SAGE_PREDICTIVE_MAINTENANCE_DB_PATH = os.getenv("SAGE_PREDICTIVE_MAINTENANCE_DB_PATH", "sage_predictive_maintenance.sqlite")

# --- DEMAND FORECASTING CONFIGURATION (Prompt 22) ---
SAGE_DEMAND_FORECASTING_DB_PATH = os.getenv("SAGE_DEMAND_FORECASTING_DB_PATH", "sage_demand_forecasting.sqlite")

# --- SUPPLIER RISK CONFIGURATION (Prompt 23) ---
SAGE_SUPPLIER_RISK_DB_PATH = os.getenv("SAGE_SUPPLIER_RISK_DB_PATH", "sage_supplier_risk.sqlite")

# --- SLA / CUSTOMER RISK INTELLIGENCE CONFIGURATION (Prompt 24) ---
SAGE_SLA_CUSTOMER_RISK_DB_PATH = os.getenv("SAGE_SLA_CUSTOMER_RISK_DB_PATH", "sage_sla_customer_risk.sqlite")
SAGE_SLA_MAX_EVIDENCE = int(os.getenv("SAGE_SLA_MAX_EVIDENCE", 1000))
SAGE_SLA_MAX_HISTORY = int(os.getenv("SAGE_SLA_MAX_HISTORY", 500))

# --- FINANCIAL IMPACT INTELLIGENCE CONFIGURATION (Prompt 25) ---
SAGE_FINANCIAL_IMPACT_DB_PATH = os.getenv("SAGE_FINANCIAL_IMPACT_DB_PATH", "sage_financial_impact.sqlite")
SAGE_FINANCIAL_IMPACT_MAX_EVIDENCE = int(os.getenv("SAGE_FINANCIAL_IMPACT_MAX_EVIDENCE", 1000))
SAGE_FINANCIAL_IMPACT_MAX_ASSESSMENTS = int(os.getenv("SAGE_FINANCIAL_IMPACT_MAX_ASSESSMENTS", 200))

# --- SUSTAINABILITY INTELLIGENCE CONFIGURATION (Prompt 26) ---
SAGE_SUSTAINABILITY_DB_PATH = os.getenv("SAGE_SUSTAINABILITY_DB_PATH", "sage_sustainability.sqlite")
SAGE_SUSTAINABILITY_MAX_EVIDENCE = int(os.getenv("SAGE_SUSTAINABILITY_MAX_EVIDENCE", 1000))
SAGE_SUSTAINABILITY_MAX_ASSESSMENTS = int(os.getenv("SAGE_SUSTAINABILITY_MAX_ASSESSMENTS", 200))

# --- MULTIMODAL SENSOR FUSION CONFIGURATION (Prompt 27) ---
SAGE_SENSOR_FUSION_DB_PATH = os.getenv("SAGE_SENSOR_FUSION_DB_PATH", "sage_sensor_fusion.sqlite")
SAGE_SENSOR_FUSION_MAX_OBSERVATIONS = int(os.getenv("SAGE_SENSOR_FUSION_MAX_OBSERVATIONS", 1000))
SAGE_SENSOR_FUSION_MAX_MODALITIES = int(os.getenv("SAGE_SENSOR_FUSION_MAX_MODALITIES", 20))
SAGE_SENSOR_FUSION_MAX_EVALUATION_WINDOW_SECONDS = int(os.getenv("SAGE_SENSOR_FUSION_MAX_EVALUATION_WINDOW_SECONDS", 86400 * 30))  # 30 days
SAGE_SENSOR_FUSION_MAX_GRAPH_DEPTH = int(os.getenv("SAGE_SENSOR_FUSION_MAX_GRAPH_DEPTH", 5))
SAGE_SENSOR_FUSION_MAX_GRAPH_NODES = int(os.getenv("SAGE_SENSOR_FUSION_MAX_GRAPH_NODES", 200))
SAGE_SENSOR_FUSION_MAX_EVIDENCE = int(os.getenv("SAGE_SENSOR_FUSION_MAX_EVIDENCE", 1000))
SAGE_SENSOR_FUSION_MAX_CORRELATION_SAMPLES = int(os.getenv("SAGE_SENSOR_FUSION_MAX_CORRELATION_SAMPLES", 5000))
SAGE_SENSOR_FUSION_MAX_ASSESSMENTS = int(os.getenv("SAGE_SENSOR_FUSION_MAX_ASSESSMENTS", 200))

# --- WHAT-IF SIMULATION INTELLIGENCE CONFIGURATION (Prompt 28) ---
SAGE_WHAT_IF_SIMULATION_DB_PATH = os.getenv("SAGE_WHAT_IF_SIMULATION_DB_PATH", "sage_what_if_simulation.sqlite")
SAGE_SIMULATION_MAX_DEPTH = int(os.getenv("SAGE_SIMULATION_MAX_DEPTH", 5))
SAGE_SIMULATION_MAX_NODES = int(os.getenv("SAGE_SIMULATION_MAX_NODES", 200))
SAGE_SIMULATION_MAX_PATHS = int(os.getenv("SAGE_SIMULATION_MAX_PATHS", 500))
SAGE_SIMULATION_MAX_EVIDENCE = int(os.getenv("SAGE_SIMULATION_MAX_EVIDENCE", 1000))
SAGE_SIMULATION_MAX_VARIABLES = int(os.getenv("SAGE_SIMULATION_MAX_VARIABLES", 100))
SAGE_SIMULATION_MAX_SCENARIOS = int(os.getenv("SAGE_SIMULATION_MAX_SCENARIOS", 200))

# --- OPTIMIZATION INTELLIGENCE CONFIGURATION (Prompt 29) ---
SAGE_OPTIMIZATION_DB_PATH = os.getenv("SAGE_OPTIMIZATION_DB_PATH", "sage_optimization.sqlite")
SAGE_OPTIMIZATION_MAX_VARIABLES = int(os.getenv("SAGE_OPTIMIZATION_MAX_VARIABLES", 100))
SAGE_OPTIMIZATION_MAX_CANDIDATES = int(os.getenv("SAGE_OPTIMIZATION_MAX_CANDIDATES", 10000))
SAGE_OPTIMIZATION_MAX_ITERATIONS = int(os.getenv("SAGE_OPTIMIZATION_MAX_ITERATIONS", 10000))
SAGE_OPTIMIZATION_MAX_OBJECTIVES = int(os.getenv("SAGE_OPTIMIZATION_MAX_OBJECTIVES", 20))
SAGE_OPTIMIZATION_MAX_CONSTRAINTS = int(os.getenv("SAGE_OPTIMIZATION_MAX_CONSTRAINTS", 500))
SAGE_OPTIMIZATION_MAX_SOLUTION_COUNT = int(os.getenv("SAGE_OPTIMIZATION_MAX_SOLUTION_COUNT", 100))
SAGE_OPTIMIZATION_MAX_GRAPH_DEPTH = int(os.getenv("SAGE_OPTIMIZATION_MAX_GRAPH_DEPTH", 5))
SAGE_OPTIMIZATION_MAX_CONTEXT_ENTITIES = int(os.getenv("SAGE_OPTIMIZATION_MAX_CONTEXT_ENTITIES", 500))
SAGE_OPTIMIZATION_MAX_EVIDENCE = int(os.getenv("SAGE_OPTIMIZATION_MAX_EVIDENCE", 1000))
SAGE_OPTIMIZATION_MAX_PROBLEMS = int(os.getenv("SAGE_OPTIMIZATION_MAX_PROBLEMS", 200))

# --- DECISION ENGINE FOUNDATION CONFIGURATION (Prompt 30) ---
SAGE_DECISION_ENGINE_DB_PATH = os.getenv("SAGE_DECISION_ENGINE_DB_PATH", "sage_decision_engine.sqlite")
SAGE_DECISION_MAX_OPTIONS = int(os.getenv("SAGE_DECISION_MAX_OPTIONS", 100))
SAGE_DECISION_MAX_CRITERIA = int(os.getenv("SAGE_DECISION_MAX_CRITERIA", 50))
SAGE_DECISION_MAX_CONSTRAINTS = int(os.getenv("SAGE_DECISION_MAX_CONSTRAINTS", 500))
SAGE_DECISION_MAX_POLICIES = int(os.getenv("SAGE_DECISION_MAX_POLICIES", 100))
SAGE_DECISION_MAX_EVIDENCE = int(os.getenv("SAGE_DECISION_MAX_EVIDENCE", 1000))
SAGE_DECISION_MAX_EVALUATIONS = int(os.getenv("SAGE_DECISION_MAX_EVALUATIONS", 200))

# --- EVIDENCE AND EXPLAINABILITY CONFIGURATION (Prompt 31) ---
SAGE_EVIDENCE_EXPLAINABILITY_DB_PATH = os.getenv("SAGE_EVIDENCE_EXPLAINABILITY_DB_PATH", "sage_evidence_explainability.sqlite")
SAGE_EXPLAINABILITY_MAX_GRAPH_DEPTH = int(os.getenv("SAGE_EXPLAINABILITY_MAX_GRAPH_DEPTH", 10))
SAGE_EXPLAINABILITY_MAX_NODES = int(os.getenv("SAGE_EXPLAINABILITY_MAX_NODES", 500))
SAGE_EXPLAINABILITY_MAX_EDGES = int(os.getenv("SAGE_EXPLAINABILITY_MAX_EDGES", 1000))
SAGE_EXPLAINABILITY_MAX_EVIDENCE_ITEMS = int(os.getenv("SAGE_EXPLAINABILITY_MAX_EVIDENCE_ITEMS", 1000))
SAGE_EXPLAINABILITY_DEFAULT_FRESHNESS_SECONDS = float(os.getenv("SAGE_EXPLAINABILITY_DEFAULT_FRESHNESS_SECONDS", 86400.0 * 7))
SAGE_EXPLAINABILITY_MAX_EXPLANATIONS = int(os.getenv("SAGE_EXPLAINABILITY_MAX_EXPLANATIONS", 200))
# --- CONFIDENCE AND UNCERTAINTY INTELLIGENCE CONFIGURATION (Prompt 32) ---
SAGE_CONFIDENCE_UNCERTAINTY_DB_PATH = os.getenv("SAGE_CONFIDENCE_UNCERTAINTY_DB_PATH", "sage_confidence_uncertainty.sqlite")
SAGE_CONFIDENCE_MAX_EVIDENCE_ITEMS = int(os.getenv("SAGE_CONFIDENCE_MAX_EVIDENCE_ITEMS", 1000))
SAGE_CONFIDENCE_MAX_ASSESSMENTS = int(os.getenv("SAGE_CONFIDENCE_MAX_ASSESSMENTS", 200))
SAGE_CONFIDENCE_MAX_BATCH_SIZE = int(os.getenv("SAGE_CONFIDENCE_MAX_BATCH_SIZE", 50))
SAGE_CONFIDENCE_MAX_HISTORY_ITEMS = int(os.getenv("SAGE_CONFIDENCE_MAX_HISTORY_ITEMS", 100))
SAGE_CONFIDENCE_DEFAULT_FRESHNESS_SECONDS = float(os.getenv("SAGE_CONFIDENCE_DEFAULT_FRESHNESS_SECONDS", 86400.0 * 7))
SAGE_CONFIDENCE_MAX_SENSITIVITY_PARAMS = int(os.getenv("SAGE_CONFIDENCE_MAX_SENSITIVITY_PARAMS", 50))
SAGE_CONFIDENCE_MAX_COMPONENTS = int(os.getenv("SAGE_CONFIDENCE_MAX_COMPONENTS", 100))

# --- SOP / RAG INTELLIGENCE CONFIGURATION (Prompt 33) ---
SAGE_SOP_RAG_DB_PATH = os.getenv("SAGE_SOP_RAG_DB_PATH", "sage_sop_rag.sqlite")
SAGE_SOP_MAX_DOC_SIZE_BYTES = int(os.getenv("SAGE_SOP_MAX_DOC_SIZE_BYTES", 5 * 1024 * 1024))  # 5 MB
SAGE_SOP_MAX_CHUNKS_PER_DOC = int(os.getenv("SAGE_SOP_MAX_CHUNKS_PER_DOC", 500))
SAGE_SOP_DEFAULT_CHUNK_SIZE_CHARS = int(os.getenv("SAGE_SOP_DEFAULT_CHUNK_SIZE_CHARS", 1000))
SAGE_SOP_DEFAULT_CHUNK_OVERLAP_CHARS = int(os.getenv("SAGE_SOP_DEFAULT_CHUNK_OVERLAP_CHARS", 150))
SAGE_SOP_MAX_RETRIEVAL_RESULTS = int(os.getenv("SAGE_SOP_MAX_RETRIEVAL_RESULTS", 50))
SAGE_SOP_DEFAULT_RETRIEVAL_LIMIT = int(os.getenv("SAGE_SOP_DEFAULT_RETRIEVAL_LIMIT", 10))
SAGE_SOP_MAX_QUERY_LENGTH_CHARS = int(os.getenv("SAGE_SOP_MAX_QUERY_LENGTH_CHARS", 2000))
SAGE_SOP_MAX_DOCUMENTS = int(os.getenv("SAGE_SOP_MAX_DOCUMENTS", 500))
SAGE_RAG_MAX_CONTEXT_TOKENS = int(os.getenv("SAGE_RAG_MAX_CONTEXT_TOKENS", 4000))
SAGE_RAG_DEFAULT_SIMILARITY_THRESHOLD = float(os.getenv("SAGE_RAG_DEFAULT_SIMILARITY_THRESHOLD", 0.05))

