# backend/tools/action_tools.py
"""
SageCommand V3 — Agent Action Tools
Enables LangGraph agents to propose, validate, and simulate structured actions
without directly generating or executing raw operational SQL statements.
"""

from typing import Dict, Any, Optional
from langchain_core.tools import tool

try:
    from core.auth import Identity
    from data.schemas.action_contract import (
        Action,
        ActionType,
        ResourceType,
        ActionTarget,
        ActionReason,
        ActionProvenance,
        CostEstimate,
        ActionStatus,
        RiskLevel,
    )
    from services.action_registry import action_registry
    from services.action_validator import action_validator
    from services.action_store import action_store
    from services.policy_service import policy_service
    from data.schemas.policy_contract import PolicyEvaluationContext
except ModuleNotFoundError:
    from backend.core.auth import Identity
    from backend.data.schemas.action_contract import (
        Action,
        ActionType,
        ResourceType,
        ActionTarget,
        ActionReason,
        ActionProvenance,
        CostEstimate,
        ActionStatus,
        RiskLevel,
    )
    from backend.services.action_registry import action_registry
    from backend.services.action_validator import action_validator
    from backend.services.action_store import action_store
    from backend.services.policy_service import policy_service
    from backend.data.schemas.policy_contract import PolicyEvaluationContext


@tool
def propose_action(
    action_type: str,
    resource_type: str,
    resource_id: str,
    parameters: Dict[str, Any],
    reason: str,
    reason_code: str = "OPERATIONAL_RECOVERY",
    estimated_cost_usd: float = 0.0,
    estimated_duration_minutes: int = 0,
    tenant_id: str = "tenant_default",
    workspace_id: str = "workspace_default",
    session_id: str = "session_default",
    plant_id: str = "plant_001"
) -> str:
    """
    Proposes a typed, validated industrial action instead of raw operational SQL.
    Available Action Types:
      ADJUST_REORDER_POINT, REORDER_INVENTORY, MOVE_INVENTORY,
      SCHEDULE_MAINTENANCE, CREATE_MAINTENANCE_WORK_ORDER, RESCHEDULE_PRODUCTION,
      CHANGE_PRODUCTION_PLAN, UPDATE_SUPPLIER_ORDER, ESCALATE_INCIDENT,
      NOTIFY_STAKEHOLDER, UPDATE_SLA_PRIORITY.
    """
    try:
        # 1. Parse and validate ActionType
        try:
            act_type_enum = ActionType(action_type.upper().strip())
        except ValueError:
            valid_types = [a.value for a in ActionType]
            return f"Error: Invalid action_type '{action_type}'. Must be one of: {', '.join(valid_types)}"

        # 2. Parse and validate ResourceType
        try:
            res_type_enum = ResourceType(resource_type.upper().strip())
        except ValueError:
            valid_resources = [r.value for r in ResourceType]
            return f"Error: Invalid resource_type '{resource_type}'. Must be one of: {', '.join(valid_resources)}"

        # 3. Build domain components
        target = ActionTarget(
            resource_type=res_type_enum,
            resource_id=resource_id.strip(),
            tenant_id=tenant_id,
            workspace_id=workspace_id,
            plant_id=plant_id
        )

        cost = CostEstimate(value=float(estimated_cost_usd), currency="USD") if estimated_cost_usd > 0 else None

        reason_obj = ActionReason(
            summary=reason.strip(),
            justification=f"Autonomous recommendation generated by agent reasoning for {resource_id}.",
            reason_code=reason_code.strip()
        )

        provenance = ActionProvenance(
            requested_by_user_id="agent_action_tool",
            source="AGENT",
            model_name="agent-evaluator-v3",
            reasoning_trace=reason
        )

        # 4. Classify risk deterministically
        system_risk = action_registry.classify_risk(
            action_type=act_type_enum,
            target=target,
            parameters=parameters,
            cost_estimate=cost
        )
        requires_approval = system_risk in [RiskLevel.HIGH, RiskLevel.CRITICAL]

        action = Action(
            tenant_id=tenant_id,
            workspace_id=workspace_id,
            session_id=session_id,
            action_type=act_type_enum,
            version="1.0",
            target=target,
            parameters=parameters,
            reason=reason_obj,
            data_mode="REAL",
            system_risk_level=system_risk,
            requires_approval=requires_approval,
            estimated_cost=cost,
            estimated_duration_minutes=estimated_duration_minutes,
            provenance=provenance,
            status=ActionStatus.PROPOSED
        )

        # 5. Execute two-layer validation
        identity = Identity(user_id="agent_action_tool", tenant_id=tenant_id, session_id=session_id)
        is_valid, checks = action_validator.validate_all(action, identity)
        failed_checks = [c for c in checks if c.status == "FAIL"]

        if not is_valid:
            action.status = ActionStatus.REJECTED
            fail_reasons = "\n".join([f"- {c.name}: {c.message}" for c in failed_checks])
            return f"ACTION REJECTED BY VALIDATION ENGINE:\n{fail_reasons}"

        # 6. Store proposed action
        action_store.save(action)

        return (
            f"ACTION PROPOSED SUCCESSFULLY:\n"
            f"Action ID: {action.action_id}\n"
            f"Type: {action.action_type.value}\n"
            f"Target: {action.target.resource_id} ({action.target.resource_type.value})\n"
            f"Deterministic Risk: {action.system_risk_level.value}\n"
            f"Requires Human Approval: {'YES' if action.requires_approval else 'NO'}\n"
            f"Status: {action.status.value}\n\n"
            f"Preview:\n{action.generate_human_preview()}"
        )

    except Exception as e:
        return f"Failed to propose action: {str(e)}"


@tool
def preview_action_impact(
    action_id: str,
    tenant_id: str = "tenant_default"
) -> str:
    """Generates a safe simulation of the expected effects and impact of a proposed action."""
    action = action_store.get_by_id(action_id, tenant_id)
    if not action:
        return f"Error: Action '{action_id}' not found for tenant '{tenant_id}'."

    sim = action_validator.generate_simulation(action)
    effects_str = "\n".join([
        f"- Resource: {e.resource} | Field: {e.field} | Before: {e.before} -> After: {e.after}"
        for e in sim.expected_effects
    ])
    return (
        f"SIMULATION PREVIEW for {action.action_id} ({action.action_type.value}):\n"
        f"Expected Effects:\n{effects_str}\n\n"
        f"Estimated Impact:\n{sim.estimated_impact}\n"
        f"Note: This was a simulated preview. Live state has not been modified."
    )


@tool
def list_supported_actions() -> str:
    """Lists all 11 supported action types with parameter schemas and risk tiers."""
    lines = ["SAGECOMMAND V3 SUPPORTED ACTION TYPES:"]
    for defn in action_registry.list_definitions():
        lines.append(
            f"\n• {defn.action_type.value} (Default Risk: {defn.default_risk.value})\n"
            f"  Description: {defn.description}\n"
            f"  Allowed Targets: {', '.join([t.value for t in defn.allowed_resource_types])}\n"
            f"  Rollback: {defn.rollback_capability.value}"
        )
    return "\n".join(lines)


@tool
def check_action_policy(
    action_id: str,
    tenant_id: str = "tenant_default"
) -> str:
    """Evaluates an existing proposed action against active system policies and returns the governance decision."""
    action = action_store.get_by_id(action_id, tenant_id)
    if not action:
        return f"Error: Action '{action_id}' not found for tenant '{tenant_id}'."

    context = PolicyEvaluationContext(
        tenant_id=tenant_id,
        workspace_id=action.workspace_id,
        session_id=action.session_id,
        user_id="agent_action_tool",
        plant_id=action.target.plant_id,
        roles=["operator"],
        data_mode=action.data_mode
    )

    decision = policy_service.evaluate(action=action, context=context, persist_decision=True)
    approval_str = f"Yes ({decision.approval_requirement.reason})" if decision.requires_approval and decision.approval_requirement else ("Yes" if decision.requires_approval else "No")

    return (
        f"POLICY EVALUATION RESULT for {action.action_id}:\n"
        f"Decision: {decision.decision.value}\n"
        f"Governing Policy: {decision.policy_id or 'None'} (v{decision.policy_version or 'N/A'})\n"
        f"Requires Approval: {approval_str}\n"
        f"Explanation: {decision.explanation}\n"
        f"Reason Codes: {', '.join(decision.reason_codes)}"
    )

