# backend/data/schemas/digital_twin_contract.py
"""
SageCommand V3 — Digital Twin Foundation Contracts (Prompt 13)
Defines deterministic domain models for virtual operational state, typed properties,
state versioning, snapshots, simulation scenarios, state comparison, conflict handling,
provenance, freshness, and validation.

Cardinal Invariant:
The Digital Twin is a deterministic virtual representation and simulation-context layer.
It never performs physical actuation, operational mutations, or bypasses the Execution Gateway.
"""

from enum import Enum
from typing import Optional, List, Dict, Any
from datetime import datetime, timezone
from pydantic import BaseModel, Field, ConfigDict

try:
    from data.schemas.ontology_contract import EntityType, EntitySource
    from data.schemas.knowledge_graph_contract import FreshnessState, FactSourceType
except ModuleNotFoundError:
    from backend.data.schemas.ontology_contract import EntityType, EntitySource
    from backend.data.schemas.knowledge_graph_contract import FreshnessState, FactSourceType


# =============================================================================
# 1. ENUMS
# =============================================================================

class TwinStateClassification(str, Enum):
    """Explicit classification of how a twin state value was obtained."""
    OBSERVED = "OBSERVED"      # Derived from actual operational source
    SIMULATED = "SIMULATED"    # Generated by simulation or scenario
    DERIVED = "DERIVED"        # Calculated from other trusted state/facts
    UNKNOWN = "UNKNOWN"        # No trustworthy classification available


class TwinConfidence(str, Enum):
    """Confidence classification for twin state values."""
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    UNKNOWN = "UNKNOWN"


class TwinConflictState(str, Enum):
    """Conflict resolution status for twin state observations."""
    NONE = "NONE"              # No conflict detected
    CONFLICT = "CONFLICT"      # Conflicting observations exist
    RESOLVED = "RESOLVED"      # Conflict was resolved deterministically


class TwinPropertyValueType(str, Enum):
    """Supported value types for twin state properties."""
    STRING = "STRING"
    INTEGER = "INTEGER"
    FLOAT = "FLOAT"
    BOOLEAN = "BOOLEAN"
    ENUM = "ENUM"
    TIMESTAMP = "TIMESTAMP"
    JSON = "JSON"


# Twin-eligible entity types — only these types may have Digital Twin state
TWIN_ELIGIBLE_ENTITY_TYPES = frozenset({
    EntityType.MACHINE,
    EntityType.EQUIPMENT,
    EntityType.ROBOT,
    EntityType.SENSOR,
    EntityType.ACTUATOR,
    EntityType.PLC,
    EntityType.CONTROLLER,
    EntityType.PRODUCTION_LINE,
    EntityType.WORK_CELL,
    EntityType.STORAGE_LOCATION,
    EntityType.INVENTORY_ITEM,
    EntityType.ENERGY_RESOURCE,
    EntityType.UTILITY,
})


# =============================================================================
# 2. CORE DOMAIN MODELS
# =============================================================================

class TwinStateProperty(BaseModel):
    """
    A single typed state property within a Digital Twin entity.
    Captures the observed/simulated value, provenance, classification, and confidence.
    """
    model_config = ConfigDict(extra="ignore")

    property_name: str = Field(..., min_length=1, max_length=128, description="State property identifier e.g. status, temperature")
    value_type: TwinPropertyValueType = Field(default=TwinPropertyValueType.STRING)
    value: Any = Field(..., description="Property value, typed per value_type")
    unit: Optional[str] = Field(None, max_length=32, description="Physical unit e.g. CELSIUS, RPM")
    classification: TwinStateClassification = Field(default=TwinStateClassification.OBSERVED)
    confidence: TwinConfidence = Field(default=TwinConfidence.UNKNOWN)
    source_type: FactSourceType = Field(default=FactSourceType.SYSTEM)
    source_id: str = Field(default="system", description="Identifier of reporting source")
    observed_at: str = Field(..., description="ISO 8601 timestamp when observed in field")
    effective_at: str = Field(..., description="ISO 8601 timestamp when value became effective")
    recorded_at: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    metadata: Dict[str, Any] = Field(default_factory=dict)


class TwinEntity(BaseModel):
    """
    Digital Twin representation of an industrial entity's virtual operational state.
    twin_id is NOT a replacement for ontology entity_id — the canonical ontology entity
    remains authoritative for identity.
    """
    model_config = ConfigDict(extra="ignore")

    twin_id: str = Field(..., description="Unique twin record identifier")
    entity_id: str = Field(..., description="Canonical ontology entity ID (authoritative)")
    tenant_id: str = Field(..., description="Mandatory tenant isolation partition")
    workspace_id: str = Field(default="workspace_default")
    plant_id: Optional[str] = None
    entity_type: EntityType = Field(..., description="Ontology entity type classification")
    properties: List[TwinStateProperty] = Field(default_factory=list, description="Current typed state properties")
    state_version: int = Field(default=1, ge=1, description="Monotonically increasing state version")
    observed_at: str = Field(..., description="Timestamp of latest observation")
    effective_at: str = Field(..., description="Timestamp when this state became effective")
    recorded_at: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    freshness: FreshnessState = Field(default=FreshnessState.UNKNOWN)
    conflict_state: TwinConflictState = Field(default=TwinConflictState.NONE)
    metadata: Dict[str, Any] = Field(default_factory=dict)


class TwinStateVersion(BaseModel):
    """Historical state version record for temporal reconstruction."""
    model_config = ConfigDict(extra="ignore")

    version_id: str = Field(..., description="Unique version record identifier")
    twin_id: str
    entity_id: str
    tenant_id: str
    state_version: int = Field(..., ge=1)
    properties: List[TwinStateProperty] = Field(default_factory=list)
    effective_at: str
    recorded_at: str
    classification: TwinStateClassification = Field(default=TwinStateClassification.OBSERVED)
    conflict_state: TwinConflictState = Field(default=TwinConflictState.NONE)


class TwinSnapshot(BaseModel):
    """
    Immutable point-in-time snapshot of Digital Twin state.
    Snapshot consistency rule: latest valid state WHERE effective_at <= snapshot_timestamp.
    """
    model_config = ConfigDict(extra="ignore")

    snapshot_id: str = Field(..., description="Unique snapshot identifier")
    tenant_id: str
    workspace_id: str = Field(default="workspace_default")
    plant_id: Optional[str] = None
    snapshot_timestamp: str = Field(..., description="ISO 8601 timestamp the snapshot represents")
    entities: List[TwinEntity] = Field(default_factory=list)
    entity_count: int = Field(default=0)
    created_at: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    created_by: str = Field(default="system")
    description: Optional[str] = None
    metadata: Dict[str, Any] = Field(default_factory=dict)
    is_immutable: bool = Field(default=True, description="Snapshots are immutable after creation")


class TwinScenario(BaseModel):
    """
    Simulation scenario: isolated state overrides based on a known snapshot.
    Scenario state NEVER silently becomes observed/real state.
    """
    model_config = ConfigDict(extra="ignore")

    scenario_id: str = Field(..., description="Unique scenario identifier")
    tenant_id: str
    workspace_id: str = Field(default="workspace_default")
    base_snapshot_id: str = Field(..., description="Reference to the baseline snapshot")
    name: str = Field(..., min_length=1, max_length=256)
    description: Optional[str] = None
    overrides: List[Dict[str, Any]] = Field(default_factory=list, description="Property overrides per entity")
    created_at: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    created_by: str = Field(default="system")
    metadata: Dict[str, Any] = Field(default_factory=dict)


class TwinStateDiff(BaseModel):
    """Structured state comparison result for a single property difference."""
    model_config = ConfigDict(extra="ignore")

    entity_id: str
    property_name: str
    old_value: Any = None
    new_value: Any = None
    old_classification: Optional[TwinStateClassification] = None
    new_classification: Optional[TwinStateClassification] = None
    old_source: Optional[str] = None
    new_source: Optional[str] = None
    old_timestamp: Optional[str] = None
    new_timestamp: Optional[str] = None


class TwinValidationIssue(BaseModel):
    """Structured Digital Twin consistency finding."""
    model_config = ConfigDict(extra="ignore")

    severity: str  # "ERROR" | "WARNING"
    issue_type: str
    entity_id: Optional[str] = None
    twin_id: Optional[str] = None
    message: str


class TwinValidationReport(BaseModel):
    """Comprehensive Digital Twin consistency validation report."""
    model_config = ConfigDict(extra="ignore")

    tenant_id: str
    timestamp: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    is_valid: bool
    error_count: int
    warning_count: int
    issues: List[TwinValidationIssue] = Field(default_factory=list)


# =============================================================================
# 3. REQUEST & RESPONSE ENVELOPES
# =============================================================================

class StateIngestRequest(BaseModel):
    """Request to ingest a state observation into the Digital Twin."""
    model_config = ConfigDict(extra="ignore")

    entity_id: str = Field(..., min_length=1)
    properties: List[Dict[str, Any]] = Field(..., min_length=1, description="List of property dicts with name, value, value_type, etc.")
    classification: TwinStateClassification = Field(default=TwinStateClassification.OBSERVED)
    source_type: FactSourceType = Field(default=FactSourceType.TELEMETRY)
    source_id: str = Field(default="system")
    observed_at: Optional[str] = None
    effective_at: Optional[str] = None
    confidence: TwinConfidence = Field(default=TwinConfidence.UNKNOWN)
    metadata: Dict[str, Any] = Field(default_factory=dict)


class SnapshotCreateRequest(BaseModel):
    """Request to create a point-in-time snapshot."""
    model_config = ConfigDict(extra="ignore")

    snapshot_timestamp: Optional[str] = None  # Defaults to now
    entity_ids: Optional[List[str]] = None  # None = all twin entities
    description: Optional[str] = None
    metadata: Dict[str, Any] = Field(default_factory=dict)


class ScenarioCreateRequest(BaseModel):
    """Request to create a simulation scenario."""
    model_config = ConfigDict(extra="ignore")

    base_snapshot_id: str = Field(..., min_length=1)
    name: str = Field(..., min_length=1, max_length=256)
    description: Optional[str] = None
    overrides: List[Dict[str, Any]] = Field(default_factory=list, description="[{entity_id, property_name, value, value_type}]")
    metadata: Dict[str, Any] = Field(default_factory=dict)


class StateCompareRequest(BaseModel):
    """Request to compare two twin states."""
    model_config = ConfigDict(extra="ignore")

    source_type: str = Field(..., description="snapshot | entity | scenario")
    source_id: str = Field(...)
    target_type: str = Field(..., description="snapshot | entity | scenario")
    target_id: str = Field(...)


class TwinEntityResponse(BaseModel):
    success: bool = True
    data: TwinEntity
    message: Optional[str] = None


class TwinHistoryResponse(BaseModel):
    success: bool = True
    data: List[TwinStateVersion]
    total_count: int


class SnapshotResponse(BaseModel):
    success: bool = True
    data: TwinSnapshot
    message: Optional[str] = None


class ScenarioResponse(BaseModel):
    success: bool = True
    data: TwinScenario
    message: Optional[str] = None


class CompareResponse(BaseModel):
    success: bool = True
    diffs: List[TwinStateDiff]
    total_changes: int


class ValidationResponse(BaseModel):
    success: bool = True
    report: TwinValidationReport
